# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 01:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='Shared',
            field=models.ManyToManyField(blank=True, related_name='SharedWith', to=settings.AUTH_USER_MODEL),
        ),
    ]
