# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171009_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='Name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
