# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_node_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accelerationcomponent',
            old_name='Accelerometer_time',
            new_name='AccelerometerTime',
        ),
    ]
