# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171028_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accelerationcomponent',
            name='AccelerometerTime',
            field=models.CharField(max_length=255),
        ),
    ]
